---
services:
  api:
    build:
      context: .
      dockerfile: identityAPI.Api/Dockerfile.dev
    container_name: identityapi-api-dev
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=identityapidb;Username=postgres;Password=postgres
      - Jwt__Key=12345678901234567890123456789012
      - Jwt__Issuer=identityAPI
      - Jwt__Audience=identityAPIUsers
    depends_on:
      - db
    tty: true
    stdin_open: true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - .:/src
    labels:
      - "com.microsoft.visualstudio.launch-url=http://localhost:5000/swagger"
      - "com.microsoft.visualstudio.debuggee.program=dotnet"
      - "com.microsoft.visualstudio.debuggee.workingdirectory=/src/identityAPI.Api"
